### PR TITLE
add typescript typings

### PR DESCRIPTION
**Pull request by n1ru4l**

### CODE REVIEW

**Comment by mathdroid** [comment]
LGTM. Could you check #6 and determine if there will be any more typing needed after #6 is merged? Thanks. @n1ru4l

**Comment by n1ru4l** [comment]
@mathdroid I am not an typescript expert but this should work 2415909

**Comment by n1ru4l** [comment]
@resir014 I also added an export for the interface

**Comment by tobloef** [comment]
Could we perhaps get this merged? Or #18, if that's more up to date.

**Pull request closed without merging**
