### PR TITLE
Add better descriptions and change variable name in example

### PR DESCRIPTION
**Pull request by mathdroid**
- [x] Change description to match https://caniuse.com/#feat=online-status
- [x] Change variable name in example to avoid confusion

### CODE REVIEW

**Comment by hanford** [comment]
@mathdroid I'd change `navigator.onLine` to `navigator.online` in both places

**Comment by mathdroid** [comment]
@hanford and why is that? Don't you think it's better to follow the spec's capitalization? https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine

**Comment by hanford** [comment]
didn't realize that casing was intentional, LGTM!

**Comment by mathdroid** [comment]
🙏 👍

**Pull request merged**
